service: aws-node-rest-api

provider:
  name: aws
  runtime: nodejs12.x
  profile: yearn_api 

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
