service: aws-node-rest-api

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${file(./awsProfile.yml):aws_profile}

plugins:
  - serverless-offline

functions:
  user_earnings:
    handler: handlers/userEarnings.userEarnings
    events:
      - http:
          path: /user/{id}/vaults/earnings
          method: get
