service: aws-node-rest-api

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${file(./awsProfile.yml):aws_profile}

plugins:
  - serverless-offline
  - serverless-domain-manager

functions:
  user-earnings:
    handler: services/user/vault/earnings/handler.handler
    events:
      - httpApi:
          path: /user/{id}/vaults/earnings
          method: get

  loanscan-link:
    handler: services/loanscan/link/handler.handler
    events:
      - httpApi:
          path: /loanscan/link
          method: get
custom:
  customDomain:
    domainName: api.yearn.tools
    stage: ci
    basePath: 'ci'
    certificateName: '*.yearn.tools'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: false